name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: run cmake
        run: |
          pwd
          cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install
          cmake --build _build

